package org.afrikcode.pes.enums;

public enum BranchErrorType {
    NO_BRANCHES,
    GET_BRANCH_ERROR,
    BRANCH_DELETE_ERROR,
    BRANCH_ACTIVATE_ERROR,
    BRANCH_DEACTIVATE_ERROR,
    ADD_BRANCH_ERROR,
    BRANCH_MANAGER_SET_ERROR
}
